<?php
	class WP_Adsense_Protector_db_schema{
		
    	public $plugin_table_prefix = "ads_prtctr_";
  		// Constructor
    function __construct() {
    }
    function wpa_check_tables(){
    	$this->create_config_tbl();
    	$this->create_bann_countries_tbl();
    	$this->create_bann_ip_tbl();
    	$this->create_clicks_tbl();
    	$this->create_code_tbl();
    	$this->create_ip_detail_tbl();
    	$this->create_pageviews_tbl();
    	$this->create_timezone_tbl();
    }
    function create_config_tbl(){
    	global $wpdb;
    	$your_db_name = $wpdb->prefix . $this->plugin_table_prefix.'config';		
		if($wpdb->get_var("show tables like '$your_db_name'") != $your_db_name) 
		{
			$sql = "CREATE TABLE IF NOT EXISTS `".$your_db_name."` (
				  	`id` bigint(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
					`max_click_limit` tinyint(4) NOT NULL,
					`max_click_lift_time_in_hour` int(11) NOT NULL,
					`max_pageviews` int(11) NOT NULL,
					`max_pageview_lift_time_in_hour` int(11) NOT NULL,
					`manual_ban_days` int(11) NOT NULL,
					`pageviews_record_limit` int(11) NOT NULL,
					`clicks_record_limit` int(11) NOT NULL,
					`timezone` int(11) NOT NULL
					) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;ALTER TABLE `$your_db_name` ADD PRIMARY KEY (`id`);";
			$sql.= "INSERT INTO `".$your_db_name."` (`id`, `max_click_limit`, `max_click_lift_time_in_hour`, `max_pageviews`, `max_pageview_lift_time_in_hour`, `manual_ban_days`, `timezone`, `pageviews_record_limit`, `clicks_record_limit`) VALUES (1, 2, 24, 20, 24, 10,37,10000,3000);";
			$sql.= "ALTER TABLE `".$your_db_name."` ADD PRIMARY KEY (`id`);ALTER TABLE `".$your_db_name."` MODIFY `id` bigint(20) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=2;
			ALTER TABLE `$your_db_name` MODIFY `id` bigint(20) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=2;";
			require_once(ABSPATH . 'wp-admin/includes/upgrade.php');
			dbDelta($sql);
		}
    }
    function create_bann_countries_tbl(){
    	global $wpdb;
    	/* ***********START ADSENS PROTECTOR CONFIG TABLE************* */
    	$your_db_name = $wpdb->prefix . $this->plugin_table_prefix.'bann_countries';		
		if($wpdb->get_var("show tables like '$your_db_name'") != $your_db_name) 
		{
			$sql = "CREATE TABLE IF NOT EXISTS `$your_db_name` (
				  `id` bigint(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
					  `country_name` text COLLATE utf8_unicode_ci NOT NULL,
					  `icon` text COLLATE utf8_unicode_ci NOT NULL,
					  `is_ban` tinyint(4) NOT NULL COMMENT '0=no, 1=yes'
					) ENGINE=MyISAM AUTO_INCREMENT=208 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
					INSERT INTO `wp_ads_prtctr_bann_countries` (`id`, `country_name`, `icon`, `is_ban`) VALUES
					(1, 'Afghanistan', 'af.png', 0),
					(2, 'Albania', 'al.png', 0),
					(3, 'Algeria', 'dz.png', 0),
					(4, 'American Samoa', 'ams.png', 0),
					(5, 'Andorra', 'ad.png', 0),
					(6, 'Angola', 'ao.png', 0),
					(7, 'Antigua and Barbuda', 'ag.png', 0),
					(8, 'Argentina', 'ar.png', 0),
					(9, 'Armenia', 'am.png', 0),
					(10, 'Aruba', 'aruba.png', 0),
					(11, 'Australia', 'au.png', 0),
					(12, 'Austria', 'at.png', 0),
					(13, 'Azerbaijan', 'az.png', 0),
					(14, 'Bahamas', 'bs.png', 0),
					(15, 'Bahrain', 'bh.png', 0),
					(16, 'Bangladesh', 'bd.png', 0),
					(17, 'Barbados', 'bb.png', 0),
					(18, 'Belarus', 'by.png', 0),
					(19, 'Belgium', 'be.png', 0),
					(20, 'Belize', 'bz.png', 0),
					(21, 'Benin', 'bj.png', 0),
					(22, 'Bermuda', 'bermuda.png', 0),
					(23, 'Bhutan', 'bt.png', 0),
					(24, 'Bolivia', 'bo.png', 0),
					(25, 'Bosnia and Herzegovina', 'ba.png', 0),
					(26, 'Botswana', 'bw.png', 0),
					(27, 'Brazil', 'br.png', 0),
					(28, 'Brunei Darussalam', 'bn.png', 0),
					(29, 'Bulgaria', 'bg.png', 0),
					(30, 'Burkina Faso', 'bf.png', 0),
					(31, 'Burundi', 'bi.png', 0),
					(32, 'Cambodia', 'kh.png', 0),
					(33, 'Cameroon', 'cm.png', 0),
					(34, 'Canada', 'ca.png', 0),
					(35, 'Cape Verde', 'cape_verde.png', 0),
					(36, 'Cayman Islands', 'cayman_islands.png', 0),
					(37, 'Central African Republic', 'cf.png', 0),
					(38, 'Chad', 'td.png', 0),
					(39, 'Chile', 'cl.png', 0),
					(40, 'China', 'cn.png', 0),
					(41, 'Colombia', 'co.png', 0),
					(42, 'Comoros', 'km.png', 0),
					(43, 'Congo', 'cg.png', 0),
					(44, 'Congo, The Democratic Republic of the', 'cg.png', 0),
					(45, 'Costa Rica', 'cr.png', 0),
					(46, 'Cote D''Ivoire', 'ci.png', 0),
					(47, 'Croatia', 'hr.png', 0),
					(48, 'Cuba', 'cu.png', 0),
					(49, 'Curacao', 'curacao.png', 0),
					(50, 'Cyprus', 'cy.png', 0),
					(51, 'Czech Republic', 'cz.png', 0),
					(52, 'Denmark', 'dk.png', 0),
					(53, 'Djibouti', 'dj.png', 0),
					(54, 'Dominica', 'dm.png', 0),
					(55, 'Dominican Republic', 'do.png', 0),
					(56, 'Ecuador', 'ec.png', 0),
					(57, 'Egypt', 'eg.png', 0),
					(58, 'El Salvador', 'sv.png', 0),
					(59, 'Estonia', 'ee.png', 0),
					(60, 'Ethiopia', 'et.png', 0),
					(61, 'Europe', '', 0),
					(62, 'Fiji', 'fj.png', 0),
					(63, 'Finland', 'fi.png', 0),
					(64, 'France', 'fr.png', 0),
					(65, 'French Guiana', 'frenchguiana.png', 0),
					(66, 'French Polynesia', 'French_Polynesia.png', 0),
					(67, 'Gabon', 'ga.png', 0),
					(68, 'Gambia', 'gm.png', 0),
					(69, 'Georgia', 'ge.png', 0),
					(70, 'Germany', 'de.png', 0),
					(71, 'Ghana', 'gh.png', 0),
					(72, 'Gibraltar', 'Gibraltar.png', 0),
					(73, 'Greece', 'gr.png', 0),
					(74, 'Grenada', 'gd.png', 0),
					(75, 'Guadeloupe', 'Guadeloupe.png', 0),
					(76, 'Guam', 'Guam.png', 0),
					(77, 'Guatemala', 'gt.png', 0),
					(78, 'Guernsey', 'Guernsey.png', 0),
					(79, 'Guinea', 'gn.png', 0),
					(80, 'Guinea-Bissau', 'gw.png', 0),
					(81, 'Guyana', 'gy.png', 0),
					(82, 'Haiti', 'ht.png', 0),
					(83, 'Honduras', 'hn.png', 0),
					(84, 'Hong Kong', 'Hong_Kong.png', 0),
					(85, 'Hungary', 'hu.png', 0),
					(86, 'Iceland', 'is.png', 0),
					(87, 'India', 'in.png', 0),
					(88, 'Indonesia', 'id.png', 0),
					(89, 'Iran, Islamic Republic of', 'Iran.png', 0),
					(90, 'Iraq', 'iq.png', 0),
					(91, 'Ireland', 'ie.png', 0),
					(92, 'Isle of Man', 'Isle_of_Mann.png', 0),
					(93, 'Israel', 'il.png', 0),
					(94, 'Italy', 'it.png', 0),
					(95, 'Jamaica', 'jm.png', 0),
					(96, 'Japan', 'jp.png', 0),
					(97, 'Jersey', 'Jersey.png', 0),
					(98, 'Jordan', 'jo.png', 0),
					(99, 'Kazakhstan', 'kz.png', 0),
					(100, 'Kenya', 'ke.png', 0),
					(101, 'Korea, Democratic People''s Republic of', 'Korea_Democratic_People_Republic.png', 0),
					(102, 'Korea, Republic of', 'Korea_Republic_of.png', 0),
					(103, 'Kuwait', 'kw.png', 0),
					(104, 'Kyrgyzstan', 'kg.png', 0),
					(105, 'Lao People''s Democratic Republic', 'la.png', 0),
					(106, 'Latvia', 'lv.png', 0),
					(107, 'Lebanon', 'lb.png', 0),
					(108, 'Lesotho', 'ls.png', 0),
					(109, 'Liberia', 'lr.png', 0),
					(110, 'Libya', 'ly.png', 0),
					(111, 'Libyan Arab Jamahiriya', 'Libya.png', 0),
					(112, 'Lithuania', 'lt.png', 0),
					(113, 'Luxembourg', 'lu.png', 0),
					(114, 'Macau', 'Macau.png', 0),
					(115, 'Macedonia', 'Macedonia.png', 0),
					(116, 'Madagascar', 'mg.png', 0),
					(117, 'Malawi', 'mw.png', 0),
					(118, 'Malaysia', 'my.png', 0),
					(119, 'Maldives', 'mv.png', 0),
					(120, 'Mali', 'ml.png', 0),
					(121, 'Malta', 'mt.png', 0),
					(122, 'Martinique', 'Martinique.png', 0),
					(123, 'Mauritania', 'mr.png', 0),
					(124, 'Mauritius', 'mu.png', 0),
					(125, 'Mayotte', 'Mayotte.png', 0),
					(126, 'Mexico', 'mx.png', 0),
					(127, 'Micronesia, Federated States of', 'Federated_States_of_Micronesia.png', 0),
					(128, 'Moldova, Republic of', 'Moldova.png', 0),
					(129, 'Mongolia', 'mn.png', 0),
					(130, 'Montenegro', 'me.png', 0),
					(131, 'Morocco', 'ma.png', 0),
					(132, 'Mozambique', 'mz.png', 0),
					(133, 'Myanmar', 'mm.png', 0),
					(134, 'Namibia', 'na.png', 0),
					(135, 'Nepal', 'np.png', 0),
					(136, 'Netherlands', 'nl.png', 0),
					(137, 'New Caledonia', 'NewCaledonia.png', 0),
					(138, 'New Zealand', 'nz.png', 0),
					(139, 'Nicaragua', 'ni.png', 0),
					(140, 'Niger', 'ne.png', 0),
					(141, 'Nigeria', 'ng.png', 0),
					(142, 'Northern Mariana Islands', 'Mariana_Islands.png', 0),
					(143, 'Norway', 'no.png', 0),
					(144, 'Oman', 'om.png', 0),
					(145, 'Pakistan', 'pk.png', 0),
					(146, 'Palestinian Territory', 'Palestine.png', 0),
					(147, 'Panama', 'pa.png', 0),
					(148, 'Papua New Guinea', 'pg.png', 0),
					(149, 'Paraguay', 'py.png', 0),
					(150, 'Peru', 'pe.png', 0),
					(151, 'Philippines', 'ph.png', 0),
					(152, 'Poland', 'pl.png', 0),
					(153, 'Portugal', 'pt.png', 0),
					(154, 'Puerto Rico', 'Puerto_Rico.png', 0),
					(155, 'Qatar', 'qa.png', 0),
					(156, 'Reunion', 'Reunion.png', 0),
					(157, 'Romania', 'ro.png', 0),
					(158, 'Russian Federation', 'ru.png', 0),
					(159, 'Rwanda', 'rw.png', 0),
					(160, 'Saint Kitts and Nevis', 'kn.png', 0),
					(161, 'Saint Lucia', 'lc.png', 0),
					(162, 'Saint Vincent and the Grenadines', 'vc.png', 0),
					(163, 'Saudi Arabia', 'sa.png', 0),
					(164, 'Senegal', 'sn.png', 0),
					(165, 'Serbia', 'rs.png', 0),
					(166, 'Seychelles', 'sc.png', 0),
					(167, 'Sierra Leone', 'sl.png', 0),
					(168, 'Singapore', 'sg.png', 0),
					(169, 'Slovakia', 'sk.png', 0),
					(170, 'Slovenia', 'si.png', 0),
					(171, 'Solomon Islands', 'sb.png', 0),
					(172, 'Somalia', 'so.png', 0),
					(173, 'South Africa', 'za.png', 0),
					(174, 'South Sudan', 'South_Sudan.png', 0),
					(175, 'Spain', 'es.png', 0),
					(176, 'Sri Lanka', 'lk.png', 0),
					(177, 'Sudan', 'sd.png', 0),
					(178, 'Suriname', 'sr.png', 0),
					(179, 'Swaziland', 'sz.png', 0),
					(180, 'Sweden', 'se.png', 0),
					(181, 'Switzerland', 'ch.png', 0),
					(182, 'Syrian Arab Republic', 'sy.png', 0),
					(183, 'Taiwan', 'taiwan.png', 0),
					(184, 'Tajikistan', 'tj.png', 0),
					(185, 'Tanzania, United Republic of', 'Tanzania.png', 0),
					(186, 'Thailand', 'th.png', 0),
					(187, 'Timor-Leste', 'tl.png', 0),
					(188, 'Togo', 'tg.png', 0),
					(189, 'Trinidad and Tobago', 'tt.png', 0),
					(190, 'Tunisia', 'tn.png', 0),
					(191, 'Turkey', 'tr.png', 0),
					(192, 'Turkmenistan', 'tm.png', 0),
					(193, 'Turks and Caicos Islands', 'Turks_and_Caicos_Islands.png', 0),
					(194, 'Uganda', 'ug.png', 0),
					(195, 'Ukraine', 'ua.png', 0),
					(196, 'United Arab Emirates', 'ae.png', 0),
					(197, 'United Kingdom', 'gb.png', 0),
					(198, 'United States', 'us.png', 0),
					(199, 'Uruguay', 'uy.png', 0),
					(200, 'Uzbekistan', 'uz.png', 0),
					(201, 'Vanuatu', 'vu.png', 0),
					(202, 'Venezuela', 'Venezuela.png', 0),
					(203, 'Vietnam', 'Vietnam.png', 0),
					(204, 'Virgin Islands, U.S.', 'United_States_Virgin_Islands.png', 0),
					(205, 'Yemen', 'ye.png', 0),
					(206, 'Zambia', 'zm.png', 0),
					(207, 'Zimbabwe', 'zw.png', 0);";
	 
			require_once(ABSPATH . 'wp-admin/includes/upgrade.php');
			dbDelta($sql);
		}
    	/* ***********START ADSENS PROTECTOR CONFIG TABLE************* */
    }
    function create_bann_ip_tbl(){
    	global $wpdb;
    	$your_db_name = $wpdb->prefix . $this->plugin_table_prefix.'bann_ip';		
		if($wpdb->get_var("show tables like '$your_db_name'") != $your_db_name) 
		{
			$sql = "CREATE TABLE IF NOT EXISTS `$your_db_name` (
				  `id` bigint(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
				  `ip` text COLLATE utf8_bin NOT NULL,
				  `number_of_block` INT NOT NULL,
				  `ban_type` tinyint(4) NOT NULL DEFAULT '0' COMMENT '1=Manual Ban,2=pageview excedded,3=clicks excedded',
				  `is_permanent_ban` tinyint(4) NOT NULL DEFAULT '0' COMMENT '0=no,1=yes',
				  `ban_lift_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
				  `insertion_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00'
				) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin;";
			require_once(ABSPATH . 'wp-admin/includes/upgrade.php');
			dbDelta($sql);
		}
    }
    function create_clicks_tbl(){
    	global $wpdb;
    	$your_db_name = $wpdb->prefix . $this->plugin_table_prefix.'clicks';		
		if($wpdb->get_var("show tables like '$your_db_name'") != $your_db_name) 
		{
			$sql = "CREATE TABLE IF NOT EXISTS `$your_db_name` (
				  `id` bigint(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
				  `referrer` text COLLATE utf8_bin NOT NULL,
				  `referrer_host` text COLLATE utf8_bin NOT NULL,
				  `user_agent_name` varchar(255) COLLATE utf8_bin NOT NULL,
				  `user_agent_type` tinyint(4) NOT NULL COMMENT '1=PC/Laptop,2=mobile,3=tablet,4=AOL,5=Facebook,6=robot',
				  `browser_version` varchar(255) COLLATE utf8_bin NOT NULL,
				  `OS` varchar(255) COLLATE utf8_bin NOT NULL,
				  `ip` bigint(20) NOT NULL,
				  `clicked_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
				) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;";
			require_once(ABSPATH . 'wp-admin/includes/upgrade.php');
			dbDelta($sql);
		}
    }    
    function create_code_tbl(){
    	global $wpdb;
    	$your_db_name = $wpdb->prefix . $this->plugin_table_prefix.'code';		
		if($wpdb->get_var("show tables like '$your_db_name'") != $your_db_name) 
		{
			$sql = "CREATE TABLE IF NOT EXISTS `$your_db_name` (
					  `id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
					  `title` text COLLATE utf8_bin NOT NULL,
					  `attr_id` text COLLATE utf8_bin NOT NULL,
					  `attr_class` text COLLATE utf8_bin NOT NULL,
					  `code` text COLLATE utf8_bin NOT NULL
					) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;";
			require_once(ABSPATH . 'wp-admin/includes/upgrade.php');
			dbDelta($sql);
		}
    }
    function create_ip_detail_tbl(){
    	global $wpdb;
    	$your_db_name = $wpdb->prefix . $this->plugin_table_prefix.'ip_detail';		
		if($wpdb->get_var("show tables like '$your_db_name'") != $your_db_name) 
		{
			$sql = "CREATE TABLE IF NOT EXISTS `$your_db_name` (
				  `id` bigint(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,				  
				  `ip` text COLLATE utf8_bin NOT NULL,
				  `country` text COLLATE utf8_bin NOT NULL,
				  `region` text COLLATE utf8_bin NOT NULL,
				  `city` text COLLATE utf8_bin NOT NULL,
				  `latitude` text COLLATE utf8_bin NOT NULL,
				  `longitude` text COLLATE utf8_bin NOT NULL,
				  `insertion_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
				) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;";
			require_once(ABSPATH . 'wp-admin/includes/upgrade.php');
			dbDelta($sql);
		}
    }  
    function create_pageviews_tbl(){
    	global $wpdb;
    	$your_db_name = $wpdb->prefix . $this->plugin_table_prefix.'pageviews';		
		if($wpdb->get_var("show tables like '$your_db_name'") != $your_db_name) 
		{
			$sql = "CREATE TABLE IF NOT EXISTS `$your_db_name` (
				  `id` bigint(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
				  `referrer` text COLLATE utf8_bin NOT NULL,
				  `referrer_host` text COLLATE utf8_bin NOT NULL,
				  `user_agent_name` varchar(255) COLLATE utf8_bin NOT NULL,
				  `user_agent_type` tinyint(4) NOT NULL COMMENT '1=PC/Laptop,2=mobile,3=tablet,4=AOL,5=Facebook,6=robot',
				  `browser_version` varchar(255) COLLATE utf8_bin NOT NULL,
				  `OS` varchar(255) COLLATE utf8_bin NOT NULL,
				  `ip` bigint(20) NOT NULL,
				  `pageview_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
				) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;";
			require_once(ABSPATH . 'wp-admin/includes/upgrade.php');
			dbDelta($sql);
		}
    }  
    function create_timezone_tbl(){
    	global $wpdb;
    	/* ***********START ADSENS PROTECTOR CONFIG TABLE************* */
    	$your_db_name = $wpdb->prefix . $this->plugin_table_prefix.'timezones';		
		if($wpdb->get_var("show tables like '$your_db_name'") != $your_db_name) 
		{
			$sql = "CREATE TABLE `wp_ads_prtctr_timezones` (
				  	`id` bigint(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
					`time_zone` text COLLATE utf8_bin NOT NULL
					) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
					INSERT INTO `$your_db_name` (`id`, `time_zone`) VALUES
					(1, 'Asia/Aden'),
					(2, 'Asia/Almaty'),
					(3, 'Asia/Amman'),
					(4, 'Asia/Anadyr'),
					(5, 'Asia/Aqtau'),
					(6, 'Asia/Aqtobe'),
					(7, 'Asia/Ashgabat'),
					(8, 'Asia/Atyrau'),
					(9, 'Asia/Baghdad'),
					(10, 'Asia/Bahrain'),
					(11, 'Asia/Baku'),
					(12, 'Asia/Bangkok'),
					(13, 'Asia/Barnaul'),
					(14, 'Asia/Beirut'),
					(15, 'Asia/Bishkek'),
					(16, 'Asia/Brunei'),
					(17, 'Asia/Chita'),
					(18, 'Asia/Choibalsan'),
					(19, 'Asia/Colombo'),
					(20, 'Asia/Damascus'),
					(21, 'Asia/Dhaka'),
					(22, 'Asia/Dili'),
					(23, 'Asia/Dubai'),
					(24, 'Asia/Dushanbe'),
					(25, 'Asia/Famagusta'),
					(26, 'Asia/Gaza'),
					(27, 'Asia/Hebron'),
					(28, 'Asia/Ho_Chi_Minh'),
					(29, 'Asia/Hong_Kong'),
					(30, 'Asia/Hovd'),
					(31, 'Asia/Irkutsk'),
					(32, 'Asia/Jakarta'),
					(33, 'Asia/Jayapura'),
					(34, 'Asia/Jerusalem'),
					(35, 'Asia/Kabul'),
					(36, 'Asia/Kamchatka'),
					(37, 'Asia/Karachi'),
					(38, 'Asia/Kathmandu'),
					(39, 'Asia/Khandyga'),
					(40, 'Asia/Kolkata'),
					(41, 'Asia/Krasnoyarsk'),
					(42, 'Asia/Kuala_Lumpur'),
					(43, 'Asia/Kuching'),
					(44, 'Asia/Kuwait'),
					(45, 'Asia/Macau'),
					(46, 'Asia/Magadan'),
					(47, 'Asia/Makassar'),
					(48, 'Asia/Manila'),
					(49, 'Asia/Muscat'),
					(50, 'Asia/Nicosia'),
					(51, 'Asia/Novokuznetsk'),
					(52, 'Asia/Novosibirsk'),
					(53, 'Asia/Omsk'),
					(54, 'Asia/Oral'),
					(55, 'Asia/Phnom_Penh'),
					(56, 'Asia/Pontianak'),
					(57, 'Asia/Pyongyang'),
					(58, 'Asia/Qatar'),
					(59, 'Asia/Qyzylorda'),
					(60, 'Asia/Riyadh'),
					(61, 'Asia/Sakhalin'),
					(62, 'Asia/Samarkand'),
					(63, 'Asia/Seoul'),
					(64, 'Asia/Shanghai'),
					(65, 'Asia/Singapore'),
					(66, 'Asia/Srednekolymsk'),
					(67, 'Asia/Taipei'),
					(68, 'Asia/Tashkent'),
					(69, 'Asia/Tbilisi'),
					(70, 'Asia/Tehran'),
					(71, 'Asia/Thimphu'),
					(72, 'Asia/Tokyo'),
					(73, 'Asia/Tomsk'),
					(74, 'Asia/Ulaanbaatar'),
					(75, 'Asia/Urumqi'),
					(76, 'Asia/Ust-Nera'),
					(77, 'Asia/Vientiane'),
					(78, 'Asia/Vladivostok'),
					(79, 'Asia/Yakutsk'),
					(80, 'Asia/Yangon'),
					(81, 'Asia/Yekaterinburg'),
					(82, 'Asia/Yerevan'),
					(83, 'Europe/Amsterdam'),
					(84, 'Europe/Andorra'),
					(85, 'Europe/Astrakhan'),
					(86, 'Europe/Athens'),
					(87, 'Europe/Belgrade'),
					(88, 'Europe/Berlin'),
					(89, 'Europe/Bratislava'),
					(90, 'Europe/Brussels'),
					(91, 'Europe/Bucharest'),
					(92, 'Europe/Budapest'),
					(93, 'Europe/Busingen'),
					(94, 'Europe/Chisinau'),
					(95, 'Europe/Copenhagen'),
					(96, 'Europe/Dublin'),
					(97, 'Europe/Gibraltar'),
					(98, 'Europe/Guernsey'),
					(99, 'Europe/Helsinki'),
					(100, 'Europe/Isle_of_Man'),
					(101, 'Europe/Istanbul'),
					(102, 'Europe/Jersey'),
					(103, 'Europe/Kaliningrad'),
					(104, 'Europe/Kiev'),
					(105, 'Europe/Kirov'),
					(106, 'Europe/Lisbon'),
					(107, 'Europe/Ljubljana'),
					(108, 'Europe/London'),
					(109, 'Europe/Luxembourg'),
					(110, 'Europe/Madrid'),
					(111, 'Europe/Malta'),
					(112, 'Europe/Mariehamn'),
					(113, 'Europe/Minsk'),
					(114, 'Europe/Monaco'),
					(115, 'Europe/Moscow'),
					(116, 'Europe/Oslo'),
					(117, 'Europe/Paris'),
					(118, 'Europe/Podgorica'),
					(119, 'Europe/Prague'),
					(120, 'Europe/Riga'),
					(121, 'Europe/Rome'),
					(122, 'Europe/Samara'),
					(123, 'Europe/San_Marino'),
					(124, 'Europe/Sarajevo'),
					(125, 'Europe/Saratov'),
					(126, 'Europe/Simferopol'),
					(127, 'Europe/Skopje'),
					(128, 'Europe/Sofia'),
					(129, 'Europe/Stockholm'),
					(130, 'Europe/Tallinn'),
					(131, 'Europe/Tirane'),
					(132, 'Europe/Ulyanovsk'),
					(133, 'Europe/Uzhgorod'),
					(134, 'Europe/Vaduz'),
					(135, 'Europe/Vatican'),
					(136, 'Europe/Vienna'),
					(137, 'Europe/Vilnius'),
					(138, 'Europe/Volgograd'),
					(139, 'Europe/Warsaw'),
					(140, 'Europe/Zagreb'),
					(141, 'Europe/Zaporozhye'),
					(142, 'Europe/Zurich'),
					(143, 'America/Adak'),
					(144, 'America/Anchorage'),
					(145, 'America/Anguilla'),
					(146, 'America/Antigua'),
					(147, 'America/Araguaina'),
					(148, 'America/Argentina/Buenos_Aires'),
					(149, 'America/Argentina/Catamarca'),
					(150, 'America/Argentina/Cordoba'),
					(151, 'America/Argentina/Jujuy'),
					(152, 'America/Argentina/La_Rioja'),
					(153, 'America/Argentina/Mendoza'),
					(154, 'America/Argentina/Rio_Gallegos'),
					(155, 'America/Argentina/Salta'),
					(156, 'America/Argentina/San_Juan'),
					(157, 'America/Argentina/San_Luis'),
					(158, 'America/Argentina/Tucuman'),
					(159, 'America/Argentina/Ushuaia'),
					(160, 'America/Aruba'),
					(161, 'America/Asuncion'),
					(162, 'America/Atikokan'),
					(163, 'America/Bahia'),
					(164, 'America/Bahia_Banderas'),
					(165, 'America/Barbados'),
					(166, 'America/Belem'),
					(167, 'America/Belize'),
					(168, 'America/Blanc-Sablon'),
					(169, 'America/Boa_Vista'),
					(170, 'America/Bogota'),
					(171, 'America/Boise'),
					(172, 'America/Cambridge_Bay'),
					(173, 'America/Campo_Grande'),
					(174, 'America/Cancun'),
					(175, 'America/Caracas'),
					(176, 'America/Cayenne'),
					(177, 'America/Cayman'),
					(178, 'America/Chicago'),
					(179, 'America/Chihuahua'),
					(180, 'America/Costa_Rica'),
					(181, 'America/Creston'),
					(182, 'America/Cuiaba'),
					(183, 'America/Curacao'),
					(184, 'America/Danmarkshavn'),
					(185, 'America/Dawson'),
					(186, 'America/Dawson_Creek'),
					(187, 'America/Denver'),
					(188, 'America/Detroit'),
					(189, 'America/Dominica'),
					(190, 'America/Edmonton'),
					(191, 'America/Eirunepe'),
					(192, 'America/El_Salvador'),
					(193, 'America/Fort_Nelson'),
					(194, 'America/Fortaleza'),
					(195, 'America/Glace_Bay'),
					(196, 'America/Godthab'),
					(197, 'America/Goose_Bay'),
					(198, 'America/Grand_Turk'),
					(199, 'America/Grenada'),
					(200, 'America/Guadeloupe'),
					(201, 'America/Guatemala'),
					(202, 'America/Guayaquil'),
					(203, 'America/Guyana'),
					(204, 'America/Halifax'),
					(205, 'America/Havana'),
					(206, 'America/Hermosillo'),
					(207, 'America/Indiana/Indianapolis'),
					(208, 'America/Indiana/Knox'),
					(209, 'America/Indiana/Marengo'),
					(210, 'America/Indiana/Petersburg'),
					(211, 'America/Indiana/Tell_City'),
					(212, 'America/Indiana/Vevay'),
					(213, 'America/Indiana/Vincennes'),
					(214, 'America/Indiana/Winamac'),
					(215, 'America/Inuvik'),
					(216, 'America/Iqaluit'),
					(217, 'America/Jamaica'),
					(218, 'America/Juneau'),
					(219, 'America/Kentucky/Louisville'),
					(220, 'America/Kentucky/Monticello'),
					(221, 'America/Kralendijk'),
					(222, 'America/La_Paz'),
					(223, 'America/Lima'),
					(224, 'America/Los_Angeles'),
					(225, 'America/Lower_Princes'),
					(226, 'America/Maceio'),
					(227, 'America/Managua'),
					(228, 'America/Manaus'),
					(229, 'America/Marigot'),
					(230, 'America/Martinique'),
					(231, 'America/Matamoros'),
					(232, 'America/Mazatlan'),
					(233, 'America/Menominee'),
					(234, 'America/Merida'),
					(235, 'America/Metlakatla'),
					(236, 'America/Mexico_City'),
					(237, 'America/Miquelon'),
					(238, 'America/Moncton'),
					(239, 'America/Monterrey'),
					(240, 'America/Montevideo'),
					(241, 'America/Montserrat'),
					(242, 'America/Nassau'),
					(243, 'America/New_York'),
					(244, 'America/Nipigon'),
					(245, 'America/Nome'),
					(246, 'America/Noronha'),
					(247, 'America/North_Dakota/Beulah'),
					(248, 'America/North_Dakota/Center'),
					(249, 'America/North_Dakota/New_Salem'),
					(250, 'America/Ojinaga'),
					(251, 'America/Panama'),
					(252, 'America/Pangnirtung'),
					(253, 'America/Paramaribo'),
					(254, 'America/Phoenix'),
					(255, 'America/Port-au-Prince'),
					(256, 'America/Port_of_Spain'),
					(257, 'America/Porto_Velho'),
					(258, 'America/Puerto_Rico'),
					(259, 'America/Punta_Arenas'),
					(260, 'America/Rainy_River'),
					(261, 'America/Rankin_Inlet'),
					(262, 'America/Recife'),
					(263, 'America/Regina'),
					(264, 'America/Resolute'),
					(265, 'America/Rio_Branco'),
					(266, 'America/Santarem'),
					(267, 'America/Santiago'),
					(268, 'America/Santo_Domingo'),
					(269, 'America/Sao_Paulo'),
					(270, 'America/Scoresbysund'),
					(271, 'America/Sitka'),
					(272, 'America/St_Barthelemy'),
					(273, 'America/St_Johns'),
					(274, 'America/St_Kitts'),
					(275, 'America/St_Lucia'),
					(276, 'America/St_Thomas'),
					(277, 'America/St_Vincent'),
					(278, 'America/Swift_Current'),
					(279, 'America/Tegucigalpa'),
					(280, 'America/Thule'),
					(281, 'America/Thunder_Bay'),
					(282, 'America/Tijuana'),
					(283, 'America/Toronto'),
					(284, 'America/Tortola'),
					(285, 'America/Vancouver'),
					(286, 'America/Whitehorse'),
					(287, 'America/Winnipeg'),
					(288, 'America/Yakutat'),
					(289, 'America/Yellowknife'),
					(290, 'Africa/Abidjan'),
					(291, 'Africa/Accra'),
					(292, 'Africa/Addis_Ababa'),
					(293, 'Africa/Algiers'),
					(294, 'Africa/Asmara'),
					(295, 'Africa/Bamako'),
					(296, 'Africa/Bangui'),
					(297, 'Africa/Banjul'),
					(298, 'Africa/Bissau'),
					(299, 'Africa/Blantyre'),
					(300, 'Africa/Brazzaville'),
					(301, 'Africa/Bujumbura'),
					(302, 'Africa/Cairo'),
					(303, 'Africa/Casablanca'),
					(304, 'Africa/Ceuta'),
					(305, 'Africa/Conakry'),
					(306, 'Africa/Dakar'),
					(307, 'Africa/Dar_es_Salaam'),
					(308, 'Africa/Djibouti'),
					(309, 'Africa/Douala'),
					(310, 'Africa/El_Aaiun'),
					(311, 'Africa/Freetown'),
					(312, 'Africa/Gaborone'),
					(313, 'Africa/Harare'),
					(314, 'Africa/Johannesburg'),
					(315, 'Africa/Juba'),
					(316, 'Africa/Kampala'),
					(317, 'Africa/Khartoum'),
					(318, 'Africa/Kigali'),
					(319, 'Africa/Kinshasa'),
					(320, 'Africa/Lagos'),
					(321, 'Africa/Libreville'),
					(322, 'Africa/Lome'),
					(323, 'Africa/Luanda'),
					(324, 'Africa/Lubumbashi'),
					(325, 'Africa/Lusaka'),
					(326, 'Africa/Malabo'),
					(327, 'Africa/Maputo'),
					(328, 'Africa/Maseru'),
					(329, 'Africa/Mbabane'),
					(330, 'Africa/Mogadishu'),
					(331, 'Africa/Monrovia'),
					(332, 'Africa/Nairobi'),
					(333, 'Africa/Ndjamena'),
					(334, 'Africa/Niamey'),
					(335, 'Africa/Nouakchott'),
					(336, 'Africa/Ouagadougou'),
					(337, 'Africa/Porto-Novo'),
					(338, 'Africa/Sao_Tome'),
					(339, 'Africa/Tripoli'),
					(340, 'Africa/Tunis'),
					(341, 'Africa/Windhoek'),
					(342, 'Antarctica/Casey'),
					(343, 'Antarctica/Davis'),
					(344, 'Antarctica/DumontDUrville'),
					(345, 'Antarctica/Macquarie'),
					(346, 'Antarctica/Mawson'),
					(347, 'Antarctica/McMurdo'),
					(348, 'Antarctica/Palmer'),
					(349, 'Antarctica/Rothera'),
					(350, 'Antarctica/Syowa'),
					(351, 'Antarctica/Troll'),
					(352, 'Antarctica/Vostok'),
					(353, 'Atlantic/Azores'),
					(354, 'Atlantic/Bermuda'),
					(355, 'Atlantic/Canary'),
					(356, 'Atlantic/Cape_Verde'),
					(357, 'Atlantic/Faroe'),
					(358, 'Atlantic/Madeira'),
					(359, 'Atlantic/Reykjavik'),
					(360, 'Atlantic/South_Georgia'),
					(361, 'Atlantic/St_Helena'),
					(362, 'Atlantic/Stanley'),
					(363, 'Australia/Adelaide'),
					(364, 'Australia/Brisbane'),
					(365, 'Australia/Broken_Hill'),
					(366, 'Australia/Currie'),
					(367, 'Australia/Darwin'),
					(368, 'Australia/Eucla'),
					(369, 'Australia/Hobart'),
					(370, 'Australia/Lindeman'),
					(371, 'Australia/Lord_Howe'),
					(372, 'Australia/Melbourne'),
					(373, 'Australia/Perth'),
					(374, 'Australia/Sydney'),
					(375, 'Indian/Antananarivo'),
					(376, 'Indian/Chagos'),
					(377, 'Indian/Christmas'),
					(378, 'Indian/Cocos'),
					(379, 'Indian/Comoro'),
					(380, 'Indian/Kerguelen'),
					(381, 'Indian/Mahe'),
					(382, 'Indian/Maldives'),
					(383, 'Indian/Mauritius'),
					(384, 'Indian/Mayotte'),
					(385, 'Indian/Reunion'),
					(386, 'Pacific/Apia'),
					(387, 'Pacific/Auckland'),
					(388, 'Pacific/Bougainville'),
					(389, 'Pacific/Chatham'),
					(390, 'Pacific/Chuuk'),
					(391, 'Pacific/Easter'),
					(392, 'Pacific/Efate'),
					(393, 'Pacific/Enderbury'),
					(394, 'Pacific/Fakaofo'),
					(395, 'Pacific/Fiji'),
					(396, 'Pacific/Funafuti'),
					(397, 'Pacific/Galapagos'),
					(398, 'Pacific/Gambier'),
					(399, 'Pacific/Guadalcanal'),
					(400, 'Pacific/Guam'),
					(401, 'Pacific/Honolulu'),
					(402, 'Pacific/Kiritimati'),
					(403, 'Pacific/Kosrae'),
					(404, 'Pacific/Kwajalein'),
					(405, 'Pacific/Majuro'),
					(406, 'Pacific/Marquesas'),
					(407, 'Pacific/Midway'),
					(408, 'Pacific/Nauru'),
					(409, 'Pacific/Niue'),
					(410, 'Pacific/Norfolk'),
					(411, 'Pacific/Noumea'),
					(412, 'Pacific/Pago_Pago'),
					(413, 'Pacific/Palau'),
					(414, 'Pacific/Pitcairn'),
					(415, 'Pacific/Pohnpei'),
					(416, 'Pacific/Port_Moresby'),
					(417, 'Pacific/Rarotonga'),
					(418, 'Pacific/Saipan'),
					(419, 'Pacific/Tahiti'),
					(420, 'Pacific/Tarawa'),
					(421, 'Pacific/Tongatapu'),
					(422, 'Pacific/Wake'),
					(423, 'Pacific/Wallis');";
	 
			require_once(ABSPATH . 'wp-admin/includes/upgrade.php');
			dbDelta($sql);
		}
    	/* ***********START ADSENS PROTECTOR CONFIG TABLE************* */
    }
    function wpa_delete_tables(){
    	global $wpdb;
    	$array=array('config','bann_countries','bann_ip','clicks','code','ip_detail','pageviews','timezones');
    	for ($i=0; $i <count($array) ; $i++) { 
    		$table_name = $wpdb->prefix . $this->plugin_table_prefix.$array[$i];
    		$sql = "DROP TABLE IF EXISTS $table_name;";
    		$wpdb->query($sql);
    		delete_option("my_plugin_db_version");
    	}
    }

}
?>